import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting database seeding...');

  // Create Event Templates
  const eventTemplates = [
    {
      name: 'Community Wellness Day',
      description: 'A comprehensive health and wellness event focusing on physical and mental health awareness',
      sdgTags: ['SDG3', 'SDG4'],
      impact_E_perParticipant: 0.001,
      impact_E_perHourPerParticipant: 0.0005,
      impact_E_perEvent: 0.01,
      impact_H_perParticipant: 0.002,
      impact_H_perHourPerParticipant: 0.001,
      impact_H_perEvent: 0.02,
      impact_Q_perParticipant: 0.001,
      impact_Q_perHourPerParticipant: 0.0005,
      impact_Q_perEvent: 0.01,
      impact_V_perParticipant: 0.001,
      impact_V_perHourPerParticipant: 0.0005,
      impact_V_perEvent: 0.01,
      impact_S_perParticipant: 0.003,
      impact_S_perHourPerParticipant: 0.0015,
      impact_S_perEvent: 0.02,
      impact_C_perParticipant: 0.001,
      impact_C_perHourPerParticipant: 0.0005,
      impact_C_perEvent: 0.01,
      gPolicyModifier: 0.0,
      minParticipants: 50,
      maxParticipants: 120,
      durationHoursDefault: 4,
      allowDurationScaling: true,
      verificationRequired: true,
      eligibilityRequirements: ['health_volunteer', 'medical_background'],
      riskLevel: 'low',
      leadTimeDays: 14,
      costPerParticipant: 15,
    },
    {
      name: 'Skills for Schools Mentoring',
      description: 'Educational mentoring program connecting professionals with students',
      sdgTags: ['SDG4', 'SDG10'],
      impact_E_perParticipant: 0.0005,
      impact_E_perHourPerParticipant: 0.0002,
      impact_E_perEvent: 0.005,
      impact_H_perParticipant: 0.004,
      impact_H_perHourPerParticipant: 0.002,
      impact_H_perEvent: 0.03,
      impact_Q_perParticipant: 0.002,
      impact_Q_perHourPerParticipant: 0.001,
      impact_Q_perEvent: 0.015,
      impact_V_perParticipant: 0.001,
      impact_V_perHourPerParticipant: 0.0005,
      impact_V_perEvent: 0.01,
      impact_S_perParticipant: 0.005,
      impact_S_perHourPerParticipant: 0.0025,
      impact_S_perEvent: 0.03,
      impact_C_perParticipant: 0.002,
      impact_C_perHourPerParticipant: 0.001,
      impact_C_perEvent: 0.015,
      gPolicyModifier: 0.0,
      minParticipants: 20,
      maxParticipants: 80,
      durationHoursDefault: 6,
      allowDurationScaling: true,
      verificationRequired: true,
      eligibilityRequirements: ['education_background', 'mentor_certified'],
      riskLevel: 'medium',
      leadTimeDays: 21,
      costPerParticipant: 25,
    },
    {
      name: 'Beach Cleanup Initiative',
      description: 'Environmental conservation event focusing on marine ecosystem protection',
      sdgTags: ['SDG14', 'SDG15'],
      impact_E_perParticipant: 0.008,
      impact_E_perHourPerParticipant: 0.004,
      impact_E_perEvent: 0.05,
      impact_H_perParticipant: 0.003,
      impact_H_perHourPerParticipant: 0.0015,
      impact_H_perEvent: 0.02,
      impact_Q_perParticipant: 0.001,
      impact_Q_perHourPerParticipant: 0.0005,
      impact_Q_perEvent: 0.01,
      impact_V_perParticipant: 0.004,
      impact_V_perHourPerParticipant: 0.002,
      impact_V_perEvent: 0.03,
      impact_S_perParticipant: 0.002,
      impact_S_perHourPerParticipant: 0.001,
      impact_S_perEvent: 0.015,
      impact_C_perParticipant: 0.001,
      impact_C_perHourPerParticipant: 0.0005,
      impact_C_perEvent: 0.01,
      gPolicyModifier: 0.0,
      minParticipants: 30,
      maxParticipants: 100,
      durationHoursDefault: 3,
      allowDurationScaling: true,
      verificationRequired: false,
      eligibilityRequirements: [],
      riskLevel: 'low',
      leadTimeDays: 7,
      costPerParticipant: 10,
    },
    {
      name: 'Policy & Ethics Training',
      description: 'Corporate governance and ethical decision-making workshop',
      sdgTags: ['SDG16'],
      impact_E_perParticipant: 0.0005,
      impact_E_perHourPerParticipant: 0.0002,
      impact_E_perEvent: 0.005,
      impact_H_perParticipant: 0.001,
      impact_H_perHourPerParticipant: 0.0005,
      impact_H_perEvent: 0.01,
      impact_Q_perParticipant: 0.003,
      impact_Q_perHourPerParticipant: 0.0015,
      impact_Q_perEvent: 0.02,
      impact_V_perParticipant: 0.001,
      impact_V_perHourPerParticipant: 0.0005,
      impact_V_perEvent: 0.01,
      impact_S_perParticipant: 0.001,
      impact_S_perHourPerParticipant: 0.0005,
      impact_S_perEvent: 0.01,
      impact_C_perParticipant: 0.002,
      impact_C_perHourPerParticipant: 0.001,
      impact_C_perEvent: 0.015,
      gPolicyModifier: 0.02, // Boosts governance score
      minParticipants: 15,
      maxParticipants: 50,
      durationHoursDefault: 2,
      allowDurationScaling: false,
      verificationRequired: true,
      eligibilityRequirements: ['management_level', 'compliance_training'],
      riskLevel: 'low',
      leadTimeDays: 14,
      costPerParticipant: 50,
    },
    {
      name: 'Digital Literacy Workshop',
      description: 'Technology skills training for underserved communities',
      sdgTags: ['SDG4', 'SDG10'],
      impact_E_perParticipant: 0.0005,
      impact_E_perHourPerParticipant: 0.0002,
      impact_E_perEvent: 0.005,
      impact_H_perParticipant: 0.003,
      impact_H_perHourPerParticipant: 0.0015,
      impact_H_perEvent: 0.02,
      impact_Q_perParticipant: 0.002,
      impact_Q_perHourPerParticipant: 0.001,
      impact_Q_perEvent: 0.015,
      impact_V_perParticipant: 0.001,
      impact_V_perHourPerParticipant: 0.0005,
      impact_V_perEvent: 0.01,
      impact_S_perParticipant: 0.004,
      impact_S_perHourPerParticipant: 0.002,
      impact_S_perEvent: 0.025,
      impact_C_perParticipant: 0.001,
      impact_C_perHourPerParticipant: 0.0005,
      impact_C_perEvent: 0.01,
      gPolicyModifier: 0.0,
      minParticipants: 25,
      maxParticipants: 60,
      durationHoursDefault: 4,
      allowDurationScaling: true,
      verificationRequired: true,
      eligibilityRequirements: ['tech_volunteer', 'teaching_experience'],
      riskLevel: 'low',
      leadTimeDays: 10,
      costPerParticipant: 20,
    },
    {
      name: 'Sustainable Agriculture Workshop',
      description: 'Training on sustainable farming practices and food security',
      sdgTags: ['SDG2', 'SDG12', 'SDG15'],
      impact_E_perParticipant: 0.006,
      impact_E_perHourPerParticipant: 0.003,
      impact_E_perEvent: 0.04,
      impact_H_perParticipant: 0.002,
      impact_H_perHourPerParticipant: 0.001,
      impact_H_perEvent: 0.015,
      impact_Q_perParticipant: 0.001,
      impact_Q_perHourPerParticipant: 0.0005,
      impact_Q_perEvent: 0.01,
      impact_V_perParticipant: 0.002,
      impact_V_perHourPerParticipant: 0.001,
      impact_V_perEvent: 0.015,
      impact_S_perParticipant: 0.003,
      impact_S_perHourPerParticipant: 0.0015,
      impact_S_perEvent: 0.02,
      impact_C_perParticipant: 0.002,
      impact_C_perHourPerParticipant: 0.001,
      impact_C_perEvent: 0.015,
      gPolicyModifier: 0.0,
      minParticipants: 20,
      maxParticipants: 40,
      durationHoursDefault: 6,
      allowDurationScaling: true,
      verificationRequired: true,
      eligibilityRequirements: ['agriculture_background', 'sustainability_certified'],
      riskLevel: 'medium',
      leadTimeDays: 21,
      costPerParticipant: 30,
    },
    {
      name: 'Mental Health Awareness Campaign',
      description: 'Community mental health support and awareness program',
      sdgTags: ['SDG3', 'SDG10'],
      impact_E_perParticipant: 0.0005,
      impact_E_perHourPerParticipant: 0.0002,
      impact_E_perEvent: 0.005,
      impact_H_perParticipant: 0.002,
      impact_H_perHourPerParticipant: 0.001,
      impact_H_perEvent: 0.015,
      impact_Q_perParticipant: 0.001,
      impact_Q_perHourPerParticipant: 0.0005,
      impact_Q_perEvent: 0.01,
      impact_V_perParticipant: 0.001,
      impact_V_perHourPerParticipant: 0.0005,
      impact_V_perEvent: 0.01,
      impact_S_perParticipant: 0.005,
      impact_S_perHourPerParticipant: 0.0025,
      impact_S_perEvent: 0.03,
      impact_C_perParticipant: 0.001,
      impact_C_perHourPerParticipant: 0.0005,
      impact_C_perEvent: 0.01,
      gPolicyModifier: 0.0,
      minParticipants: 30,
      maxParticipants: 80,
      durationHoursDefault: 3,
      allowDurationScaling: true,
      verificationRequired: true,
      eligibilityRequirements: ['mental_health_training', 'counseling_certified'],
      riskLevel: 'medium',
      leadTimeDays: 14,
      costPerParticipant: 25,
    },
    {
      name: 'Renewable Energy Education',
      description: 'Workshop on clean energy solutions and climate action',
      sdgTags: ['SDG7', 'SDG13'],
      impact_E_perParticipant: 0.007,
      impact_E_perHourPerParticipant: 0.0035,
      impact_E_perEvent: 0.05,
      impact_H_perParticipant: 0.002,
      impact_H_perHourPerParticipant: 0.001,
      impact_H_perEvent: 0.015,
      impact_Q_perParticipant: 0.001,
      impact_Q_perHourPerParticipant: 0.0005,
      impact_Q_perEvent: 0.01,
      impact_V_perParticipant: 0.002,
      impact_V_perHourPerParticipant: 0.001,
      impact_V_perEvent: 0.015,
      impact_S_perParticipant: 0.002,
      impact_S_perHourPerParticipant: 0.001,
      impact_S_perEvent: 0.015,
      impact_C_perParticipant: 0.001,
      impact_C_perHourPerParticipant: 0.0005,
      impact_C_perEvent: 0.01,
      gPolicyModifier: 0.0,
      minParticipants: 25,
      maxParticipants: 60,
      durationHoursDefault: 4,
      allowDurationScaling: true,
      verificationRequired: false,
      eligibilityRequirements: ['energy_background', 'environmental_certified'],
      riskLevel: 'low',
      leadTimeDays: 10,
      costPerParticipant: 20,
    },
    // Environmental (E) specific events
    {
      name: 'Ocean Cleanup Initiative',
      description: 'Marine ecosystem protection and ocean waste cleanup',
      sdgTags: ['SDG14', 'SDG15'],
      impact_E_perParticipant: 0.01,
      impact_E_perHourPerParticipant: 0.005,
      impact_E_perEvent: 0.08,
      impact_H_perParticipant: 0.001,
      impact_H_perHourPerParticipant: 0.0005,
      impact_H_perEvent: 0.01,
      impact_Q_perParticipant: 0.0005,
      impact_Q_perHourPerParticipant: 0.0002,
      impact_Q_perEvent: 0.005,
      impact_V_perParticipant: 0.001,
      impact_V_perHourPerParticipant: 0.0005,
      impact_V_perEvent: 0.01,
      impact_S_perParticipant: 0.001,
      impact_S_perHourPerParticipant: 0.0005,
      impact_S_perEvent: 0.01,
      impact_C_perParticipant: 0.0005,
      impact_C_perHourPerParticipant: 0.0002,
      impact_C_perEvent: 0.005,
      gPolicyModifier: 0.0,
      minParticipants: 20,
      maxParticipants: 50,
      durationHoursDefault: 6,
      allowDurationScaling: true,
      verificationRequired: false,
      eligibilityRequirements: ['environmental_awareness'],
      riskLevel: 'low',
      leadTimeDays: 7,
      costPerParticipant: 15,
    },
    {
      name: 'Green Building Workshop',
      description: 'Sustainable construction and energy-efficient building practices',
      sdgTags: ['SDG7', 'SDG11', 'SDG13'],
      impact_E_perParticipant: 0.008,
      impact_E_perHourPerParticipant: 0.004,
      impact_E_perEvent: 0.06,
      impact_H_perParticipant: 0.002,
      impact_H_perHourPerParticipant: 0.001,
      impact_H_perEvent: 0.015,
      impact_Q_perParticipant: 0.001,
      impact_Q_perHourPerParticipant: 0.0005,
      impact_Q_perEvent: 0.01,
      impact_V_perParticipant: 0.001,
      impact_V_perHourPerParticipant: 0.0005,
      impact_V_perEvent: 0.01,
      impact_S_perParticipant: 0.001,
      impact_S_perHourPerParticipant: 0.0005,
      impact_S_perEvent: 0.01,
      impact_C_perParticipant: 0.0005,
      impact_C_perHourPerParticipant: 0.0002,
      impact_C_perEvent: 0.005,
      gPolicyModifier: 0.0,
      minParticipants: 15,
      maxParticipants: 40,
      durationHoursDefault: 8,
      allowDurationScaling: true,
      verificationRequired: true,
      eligibilityRequirements: ['construction_background', 'sustainability_certified'],
      riskLevel: 'medium',
      leadTimeDays: 14,
      costPerParticipant: 35,
    },
    // Social (S) specific events
    {
      name: 'Food Security Program',
      description: 'Community food distribution and hunger relief initiative',
      sdgTags: ['SDG1', 'SDG2'],
      impact_E_perParticipant: 0.001,
      impact_E_perHourPerParticipant: 0.0005,
      impact_E_perEvent: 0.01,
      impact_H_perParticipant: 0.003,
      impact_H_perHourPerParticipant: 0.0015,
      impact_H_perEvent: 0.02,
      impact_Q_perParticipant: 0.001,
      impact_Q_perHourPerParticipant: 0.0005,
      impact_Q_perEvent: 0.01,
      impact_V_perParticipant: 0.002,
      impact_V_perHourPerParticipant: 0.001,
      impact_V_perEvent: 0.015,
      impact_S_perParticipant: 0.008,
      impact_S_perHourPerParticipant: 0.004,
      impact_S_perEvent: 0.05,
      impact_C_perParticipant: 0.002,
      impact_C_perHourPerParticipant: 0.001,
      impact_C_perEvent: 0.015,
      gPolicyModifier: 0.0,
      minParticipants: 40,
      maxParticipants: 100,
      durationHoursDefault: 4,
      allowDurationScaling: true,
      verificationRequired: true,
      eligibilityRequirements: ['food_handling_certified', 'community_service'],
      riskLevel: 'low',
      leadTimeDays: 5,
      costPerParticipant: 12,
    },
    {
      name: 'Gender Equality Workshop',
      description: 'Promoting gender equality and women empowerment',
      sdgTags: ['SDG5', 'SDG10'],
      impact_E_perParticipant: 0.0005,
      impact_E_perHourPerParticipant: 0.0002,
      impact_E_perEvent: 0.005,
      impact_H_perParticipant: 0.001,
      impact_H_perHourPerParticipant: 0.0005,
      impact_H_perEvent: 0.01,
      impact_Q_perParticipant: 0.001,
      impact_Q_perHourPerParticipant: 0.0005,
      impact_Q_perEvent: 0.01,
      impact_V_perParticipant: 0.001,
      impact_V_perHourPerParticipant: 0.0005,
      impact_V_perEvent: 0.01,
      impact_S_perParticipant: 0.01,
      impact_S_perHourPerParticipant: 0.005,
      impact_S_perEvent: 0.08,
      impact_C_perParticipant: 0.003,
      impact_C_perHourPerParticipant: 0.0015,
      impact_C_perEvent: 0.02,
      gPolicyModifier: 0.0,
      minParticipants: 20,
      maxParticipants: 60,
      durationHoursDefault: 6,
      allowDurationScaling: true,
      verificationRequired: true,
      eligibilityRequirements: ['gender_studies_background', 'diversity_training'],
      riskLevel: 'medium',
      leadTimeDays: 21,
      costPerParticipant: 28,
    },
    // Governance (G) specific events
    {
      name: 'Anti-Corruption Training',
      description: 'Corporate ethics and anti-corruption compliance training',
      sdgTags: ['SDG16'],
      impact_E_perParticipant: 0.0002,
      impact_E_perHourPerParticipant: 0.0001,
      impact_E_perEvent: 0.002,
      impact_H_perParticipant: 0.0005,
      impact_H_perHourPerParticipant: 0.0002,
      impact_H_perEvent: 0.005,
      impact_Q_perParticipant: 0.0005,
      impact_Q_perHourPerParticipant: 0.0002,
      impact_Q_perEvent: 0.005,
      impact_V_perParticipant: 0.001,
      impact_V_perHourPerParticipant: 0.0005,
      impact_V_perEvent: 0.01,
      impact_S_perParticipant: 0.001,
      impact_S_perHourPerParticipant: 0.0005,
      impact_S_perEvent: 0.01,
      impact_C_perParticipant: 0.0005,
      impact_C_perHourPerParticipant: 0.0002,
      impact_C_perEvent: 0.005,
      gPolicyModifier: 0.15,
      minParticipants: 10,
      maxParticipants: 30,
      durationHoursDefault: 8,
      allowDurationScaling: true,
      verificationRequired: true,
      eligibilityRequirements: ['compliance_training', 'ethics_certified'],
      riskLevel: 'low',
      leadTimeDays: 30,
      costPerParticipant: 50,
    },
    {
      name: 'Partnership Development Workshop',
      description: 'Building strategic partnerships for sustainable development',
      sdgTags: ['SDG17'],
      impact_E_perParticipant: 0.0005,
      impact_E_perHourPerParticipant: 0.0002,
      impact_E_perEvent: 0.005,
      impact_H_perParticipant: 0.001,
      impact_H_perHourPerParticipant: 0.0005,
      impact_H_perEvent: 0.01,
      impact_Q_perParticipant: 0.001,
      impact_Q_perHourPerParticipant: 0.0005,
      impact_Q_perEvent: 0.01,
      impact_V_perParticipant: 0.002,
      impact_V_perHourPerParticipant: 0.001,
      impact_V_perEvent: 0.015,
      impact_S_perParticipant: 0.002,
      impact_S_perHourPerParticipant: 0.001,
      impact_S_perEvent: 0.015,
      impact_C_perParticipant: 0.003,
      impact_C_perHourPerParticipant: 0.0015,
      impact_C_perEvent: 0.02,
      gPolicyModifier: 0.1,
      minParticipants: 15,
      maxParticipants: 40,
      durationHoursDefault: 6,
      allowDurationScaling: true,
      verificationRequired: true,
      eligibilityRequirements: ['partnership_experience', 'business_development'],
      riskLevel: 'medium',
      leadTimeDays: 21,
      costPerParticipant: 40,
    },
  ];

  console.log('📝 Creating event templates...');
  for (const template of eventTemplates) {
    await prisma.eventTemplate.create({
      data: template,
    });
  }

  console.log('✅ Event templates created successfully!');

  // Create a sample organization metric snapshot
  console.log('📊 Creating sample organization metric snapshot...');
  await prisma.organizationMetricSnapshot.create({
    data: {
      totalMembers: 150,
      activeMembers: 120,
      totalHours: 2500,
      verifiedEvents: 45,
      E: 0.2,
      H: 0.15,
      Q: 0.045,
      V: 0.0,
      S: 0.0,
      C: 0.0,
      G: 1.0,
      dataQualityScore: 0.85,
    },
  });

  console.log('✅ Sample organization metric snapshot created!');
  console.log('🎉 Database seeding completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Error during seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
