'use client';

import React, { useState } from 'react';
import { 
  Lightbulb, 
  Target, 
  Users, 
  Clock, 
  DollarSign, 
  Calendar,
  AlertTriangle,
  CheckCircle,
  Plus,
  Download,
  X
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Switch } from '@/components/ui/switch';
import { SuggestionRequest, SuggestionResult, SuggestedEvent } from '@/lib/esg/suggestion/types';
import { getSDGOptions } from '@/lib/esg/suggestion/sdg-mapping';
import { getSDGColor } from '@/lib/utils';

interface SuggestionPanelProps {
  organizationId: string;
}

export default function SuggestionPanel({ organizationId }: SuggestionPanelProps) {
  const [formData, setFormData] = useState<SuggestionRequest>({
    focus: {},
    targets: {},
    constraints: {},
  });
  
  const [selectedEvents, setSelectedEvents] = useState<Set<string>>(new Set());
  const [selectedSDGs, setSelectedSDGs] = useState<string[]>([]);
  
  const [result, setResult] = useState<SuggestionResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setResult(null); // Clear previous results
    setSelectedEvents(new Set()); // Clear previous selections
    
    try {
      const response = await fetch('/api/esg/suggest', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          ...formData,
          focus: {
            ...formData.focus,
            sdgs: selectedSDGs.length > 0 ? selectedSDGs : formData.focus.sdgs,
          },
          organizationId,
        }),
      });
      
      const data = await response.json();
      
      if (data.success) {
        setResult(data.data);
      } else {
        setError(data.error || 'Failed to generate suggestions');
      }
    } catch (err) {
      setError('Network error occurred');
    } finally {
      setLoading(false);
    }
  };

  const handleCreateDrafts = async () => {
    if (!result || selectedEvents.size === 0) {
      alert('Please select at least one event to create drafts');
      return;
    }
    
    try {
      const selectedEventIds = Array.from(selectedEvents);
      const selectedEventsData = result.plan.filter(event => 
        selectedEventIds.includes(event.templateId)
      );
      
      const drafts = selectedEventsData.map(event => ({
        templateId: event.templateId,
        participants: event.participants,
        durationHours: event.durationHours,
        sdgs: event.sdgs,
        notes: `Generated by suggestion engine`,
      }));
      
      const response = await fetch('/api/esg/drafts', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ 
          drafts,
          organizationId,
        }),
      });
      
      const data = await response.json();
      
      if (data.success) {
        alert(`Successfully created ${data.data.count} draft events!`);
        setSelectedEvents(new Set());
      } else {
        alert('Failed to create draft events');
      }
    } catch (err) {
      alert('Error creating draft events');
    }
  };

  return (
    <div className="space-y-6">
      {/* Suggestion Form */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center">
            <Lightbulb className="w-5 h-5 mr-2 text-yellow-600" />
            Event Planning Suggestion Engine
          </CardTitle>
          <CardDescription>
            Get AI-powered recommendations for events that will help you meet your ESG targets
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-6">
            {/* Focus Section */}
            <div className="space-y-4">
              <h3 className="text-lg font-semibold">Focus Area</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <Label htmlFor="band">Primary Focus Band</Label>
                    <Select
                      value={formData.focus.band || ''}
                      onValueChange={(value) => {
                        setFormData(prev => ({
                          ...prev,
                          focus: { ...prev.focus, band: value as any }
                        }));
                        setSelectedSDGs([]); // Clear SDG selections when band changes
                        setResult(null); // Clear previous results
                        setSelectedEvents(new Set()); // Clear previous event selections
                      }}
                    >
                    <SelectTrigger>
                      <SelectValue placeholder="Select focus band" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="E">Environmental (E)</SelectItem>
                      <SelectItem value="S">Social (S)</SelectItem>
                      <SelectItem value="G">Governance (G)</SelectItem>
                      <SelectItem value="SEG_overall">Overall ESG</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label htmlFor="sdgs">SDG Focus (Optional)</Label>
                  <div className="relative">
                    <Select
                      value=""
                      onValueChange={(value) => {
                        if (value === 'all') {
                          setSelectedSDGs(getSDGOptions(formData.focus.band).map(s => s.value));
                        } else if (value === 'none') {
                          setSelectedSDGs([]);
                        } else if (value && !selectedSDGs.includes(value)) {
                          setSelectedSDGs([...selectedSDGs, value]);
                        }
                        // Clear results when SDG selections change
                        setResult(null);
                        setSelectedEvents(new Set());
                      }}
                    >
                      <SelectTrigger className="w-full">
                        <SelectValue placeholder={`${selectedSDGs.length > 0 ? `${selectedSDGs.length} SDGs selected` : 'Select SDGs'}`} />
                      </SelectTrigger>
                      <SelectContent className="max-h-60 overflow-y-auto">
                        <SelectItem value="all" className="font-semibold">
                          <div className="flex items-center space-x-2">
                            <CheckCircle className="w-4 h-4 text-green-600" />
                            <span>Select All SDGs</span>
                          </div>
                        </SelectItem>
                        <SelectItem value="none" className="font-semibold">
                          <div className="flex items-center space-x-2">
                            <X className="w-4 h-4 text-red-600" />
                            <span>Clear All</span>
                          </div>
                        </SelectItem>
                        <div className="border-t my-1" />
                        {getSDGOptions(formData.focus.band).map(sdg => {
                          const isSelected = selectedSDGs.includes(sdg.value);
                          return (
                            <SelectItem 
                              key={sdg.value} 
                              value={sdg.value}
                              className={isSelected ? "bg-blue-50" : ""}
                            >
                              <div className="flex items-center space-x-3 w-full">
                                <input
                                  type="checkbox"
                                  checked={isSelected}
                                  onChange={() => {}} // Handled by onValueChange
                                  className="w-4 h-4 text-blue-600 rounded"
                                />
                                <div 
                                  className="w-4 h-4 rounded-full flex-shrink-0"
                                  style={{ backgroundColor: getSDGColor(parseInt(sdg.value.replace('SDG', ''))) }}
                                />
                                <span className="flex-1">{sdg.label}</span>
                                {isSelected && <CheckCircle className="w-4 h-4 text-blue-600" />}
                              </div>
                            </SelectItem>
                          );
                        })}
                      </SelectContent>
                    </Select>
                  </div>
                  
                  {/* Selected SDGs Display */}
                  {selectedSDGs.length > 0 && (
                    <div className="mt-3">
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-sm font-medium text-gray-700">Selected SDGs:</span>
                        <Button
                          type="button"
                          variant="ghost"
                          size="sm"
                          onClick={() => {
                            setSelectedSDGs([]);
                            setResult(null);
                            setSelectedEvents(new Set());
                          }}
                          className="text-red-600 hover:text-red-700 hover:bg-red-50"
                        >
                          <X className="w-3 h-3 mr-1" />
                          Clear All
                        </Button>
                      </div>
                      <div className="flex flex-wrap gap-2">
                        {selectedSDGs.map(sdgValue => {
                          const sdg = getSDGOptions(formData.focus.band).find(s => s.value === sdgValue);
                          const sdgNumber = parseInt(sdgValue.replace('SDG', ''));
                          return (
                            <div
                              key={sdgValue}
                              className="group inline-flex items-center space-x-2 px-3 py-2 rounded-full text-sm font-medium text-white shadow-sm hover:shadow-md transition-all duration-200"
                              style={{ backgroundColor: getSDGColor(sdgNumber) }}
                            >
                              <div 
                                className="w-2 h-2 rounded-full bg-white bg-opacity-30"
                              />
                              <span>{sdg?.label || sdgValue}</span>
                              <button
                                type="button"
                                onClick={() => {
                                  setSelectedSDGs(selectedSDGs.filter(s => s !== sdgValue));
                                  setResult(null);
                                  setSelectedEvents(new Set());
                                }}
                                className="ml-1 hover:bg-white hover:bg-opacity-20 rounded-full p-1 transition-colors duration-200"
                              >
                                <X className="w-3 h-3" />
                              </button>
                            </div>
                          );
                        })}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </div>

            {/* Targets Section */}
            <div className="space-y-4">
              <h3 className="text-lg font-semibold">Targets</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                <div>
                  <Label htmlFor="hours">Target Hours</Label>
                  <Input
                    id="hours"
                    type="number"
                    placeholder="e.g., 500"
                    value={formData.targets.hours || ''}
                    onChange={(e) => setFormData(prev => ({
                      ...prev,
                      targets: { ...prev.targets, hours: e.target.value ? Number(e.target.value) : undefined }
                    }))}
                  />
                </div>
                <div>
                  <Label htmlFor="participants">Target Participants</Label>
                  <Input
                    id="participants"
                    type="number"
                    placeholder="e.g., 100"
                    value={formData.targets.participants || ''}
                    onChange={(e) => setFormData(prev => ({
                      ...prev,
                      targets: { ...prev.targets, participants: e.target.value ? Number(e.target.value) : undefined }
                    }))}
                  />
                </div>
                <div>
                  <Label htmlFor="scoreDelta">Score Delta</Label>
                  <Input
                    id="scoreDelta"
                    type="number"
                    placeholder="e.g., 10"
                    value={formData.targets.orgScoreDelta || ''}
                    onChange={(e) => setFormData(prev => ({
                      ...prev,
                      targets: { ...prev.targets, orgScoreDelta: e.target.value ? Number(e.target.value) : undefined }
                    }))}
                  />
                </div>
              </div>
            </div>

            {/* Constraints Section */}
            <div className="space-y-4">
              <h3 className="text-lg font-semibold">Constraints</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                <div>
                  <Label htmlFor="budget">Budget ($)</Label>
                  <Input
                    id="budget"
                    type="number"
                    placeholder="e.g., 5000"
                    value={formData.constraints?.budget || ''}
                    onChange={(e) => setFormData(prev => ({
                      ...prev,
                      constraints: { ...prev.constraints, budget: e.target.value ? Number(e.target.value) : undefined }
                    }))}
                  />
                </div>
                <div>
                  <Label htmlFor="maxEvents">Max Events</Label>
                  <Input
                    id="maxEvents"
                    type="number"
                    placeholder="e.g., 5"
                    value={formData.constraints?.maxEvents || ''}
                    onChange={(e) => setFormData(prev => ({
                      ...prev,
                      constraints: { ...prev.constraints, maxEvents: e.target.value ? Number(e.target.value) : undefined }
                    }))}
                  />
                </div>
                <div>
                  <Label htmlFor="riskLevel">Risk Level</Label>
                  <Select 
                    value={formData.constraints?.riskAllowed?.join(',') || ''} 
                    onValueChange={(value) => setFormData(prev => ({
                      ...prev,
                      constraints: { 
                        ...prev.constraints, 
                        riskAllowed: value ? value.split(',') as any : undefined 
                      }
                    }))}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select risk levels" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="low">Low Risk Only</SelectItem>
                      <SelectItem value="low,medium">Low & Medium</SelectItem>
                      <SelectItem value="low,medium,high">All Risk Levels</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="flex items-center space-x-2">
                  <Switch
                    id="weekendsOnly"
                    checked={formData.constraints?.weekendsOnly || false}
                    onCheckedChange={(checked) => setFormData(prev => ({
                      ...prev,
                      constraints: { ...prev.constraints, weekendsOnly: checked as boolean }
                    }))}
                  />
                  <Label htmlFor="weekendsOnly">Weekends Only</Label>
                </div>
              </div>
            </div>

            <Button 
              type="submit" 
              disabled={loading}
              className="w-full bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700"
            >
              {loading ? 'Generating Suggestions...' : 'Generate Suggestions'}
            </Button>
          </form>
        </CardContent>
      </Card>

      {/* Results Section */}
      {result && (
        <div className="space-y-6">
          {/* Summary */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center">
                <Target className="w-5 h-5 mr-2 text-green-600" />
                Suggestion Summary
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
                <div className="text-center">
                  <div className="text-2xl font-bold text-blue-600">{result.totals.hours}</div>
                  <div className="text-sm text-gray-600">Total Hours</div>
                </div>
                <div className="text-center">
                  <div className="text-2xl font-bold text-green-600">{result.totals.participants}</div>
                  <div className="text-sm text-gray-600">Participants</div>
                </div>
                <div className="text-center">
                  <div className="text-2xl font-bold text-purple-600">${result.totals.cost}</div>
                  <div className="text-sm text-gray-600">Total Cost</div>
                </div>
                <div className="text-center">
                  <div className="text-2xl font-bold text-orange-600">{result.predictedDelta.overall.toFixed(1)}</div>
                  <div className="text-sm text-gray-600">Score Delta</div>
                </div>
              </div>

              {/* SDGs Covered */}
              <div className="mb-4">
                <h4 className="font-semibold mb-2">SDGs Covered:</h4>
                <div className="flex flex-wrap gap-2">
                  {result.sdgsCovered.map(sdg => (
                    <Badge key={sdg} variant="secondary">{sdg}</Badge>
                  ))}
                </div>
              </div>

              {/* Target Achievement */}
              <div className="space-y-2">
                <h4 className="font-semibold">Target Achievement:</h4>
                <div className="flex items-center space-x-2">
                  {result.meets.hours !== undefined && (
                    <div className="flex items-center space-x-1">
                      {result.meets.hours ? (
                        <CheckCircle className="w-4 h-4 text-green-600" />
                      ) : (
                        <AlertTriangle className="w-4 h-4 text-yellow-600" />
                      )}
                      <span className="text-sm">Hours Target</span>
                    </div>
                  )}
                  {result.meets.participants !== undefined && (
                    <div className="flex items-center space-x-1">
                      {result.meets.participants ? (
                        <CheckCircle className="w-4 h-4 text-green-600" />
                      ) : (
                        <AlertTriangle className="w-4 h-4 text-yellow-600" />
                      )}
                      <span className="text-sm">Participants Target</span>
                    </div>
                  )}
                  {result.meets.orgScoreDelta !== undefined && (
                    <div className="flex items-center space-x-1">
                      {result.meets.orgScoreDelta ? (
                        <CheckCircle className="w-4 h-4 text-green-600" />
                      ) : (
                        <AlertTriangle className="w-4 h-4 text-yellow-600" />
                      )}
                      <span className="text-sm">Score Delta Target</span>
                    </div>
                  )}
                </div>
              </div>

              {/* Warnings */}
              {result.warnings.length > 0 && (
                <div className="mt-4 p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
                  <h4 className="font-semibold text-yellow-800 mb-2">Warnings:</h4>
                  <ul className="space-y-1">
                    {result.warnings.map((warning, index) => (
                      <li key={index} className="text-sm text-yellow-700">• {warning}</li>
                    ))}
                  </ul>
                </div>
              )}

              <div className="mt-6">
                <Button 
                  onClick={handleCreateDrafts}
                  disabled={selectedEvents.size === 0}
                  className="bg-gradient-to-r from-green-600 to-blue-600 hover:from-green-700 hover:to-blue-700 disabled:opacity-50"
                >
                  <Plus className="w-4 h-4 mr-2" />
                  Create Draft Events ({selectedEvents.size} selected)
                </Button>
              </div>
            </CardContent>
          </Card>

          {/* Suggested Events */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold">Suggested Events</h3>
            {result.plan.map((event, index) => (
              <EventCard 
                key={index} 
                event={event} 
                isSelected={selectedEvents.has(event.templateId)}
                onToggle={(templateId) => {
                  const newSelected = new Set(selectedEvents);
                  if (newSelected.has(templateId)) {
                    newSelected.delete(templateId);
                  } else {
                    newSelected.add(templateId);
                  }
                  setSelectedEvents(newSelected);
                }}
              />
            ))}
          </div>
        </div>
      )}

      {/* Error Display */}
      {error && (
        <Card className="border-red-200 bg-red-50">
          <CardContent className="p-4">
            <div className="flex items-center space-x-2 text-red-800">
              <AlertTriangle className="w-5 h-5" />
              <span className="font-semibold">Error:</span>
              <span>{error}</span>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}

function EventCard({ 
  event, 
  isSelected, 
  onToggle 
}: { 
  event: SuggestedEvent; 
  isSelected: boolean;
  onToggle: (templateId: string) => void;
}) {
  return (
    <Card className={isSelected ? "ring-2 ring-blue-500 bg-blue-50" : ""}>
      <CardContent className="p-6">
        <div className="flex items-start justify-between mb-4">
          <div className="flex-1">
            <div className="flex items-center space-x-2 mb-2">
              <input
                type="checkbox"
                checked={isSelected}
                onChange={() => onToggle(event.templateId)}
                className="w-4 h-4 text-blue-600 rounded"
              />
              <h4 className="font-semibold text-lg">{event.name}</h4>
            </div>
            <p className="text-sm text-gray-600 mb-2">
              {getEventDescription(event.name)}
            </p>
            <div className="flex flex-wrap gap-2">
              {event.sdgs.map(sdg => (
                <Badge key={sdg} variant="outline">{sdg}</Badge>
              ))}
            </div>
          </div>
          <div className="text-right ml-4">
            <div className="text-2xl font-bold text-blue-600">{event.participants}</div>
            <div className="text-sm text-gray-600">participants</div>
          </div>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mb-4">
          <div className="text-center">
            <div className="text-lg font-semibold text-gray-700">{event.durationHours}h</div>
            <div className="text-xs text-gray-600">Duration</div>
          </div>
          <div className="text-center">
            <div className="text-lg font-semibold text-green-600">{event.predictedDelta.E.toFixed(2)}</div>
            <div className="text-xs text-gray-600">ΔE</div>
          </div>
          <div className="text-center">
            <div className="text-lg font-semibold text-blue-600">{event.predictedDelta.H.toFixed(2)}</div>
            <div className="text-xs text-gray-600">ΔH</div>
          </div>
          <div className="text-center">
            <div className="text-lg font-semibold text-purple-600">{event.predictedDelta.overall.toFixed(1)}</div>
            <div className="text-xs text-gray-600">Overall Δ</div>
          </div>
          <div className="text-center">
            <div className="text-lg font-semibold text-orange-600">${(event.participants * 25).toFixed(0)}</div>
            <div className="text-xs text-gray-600">Est. Cost</div>
          </div>
        </div>

        {event.warnings && event.warnings.length > 0 && (
          <div className="mt-4 p-3 bg-yellow-50 border border-yellow-200 rounded-lg">
            <div className="flex items-start space-x-2">
              <AlertTriangle className="w-4 h-4 text-yellow-600 mt-0.5" />
              <div>
                <div className="text-sm font-semibold text-yellow-800">Warnings:</div>
                <ul className="text-sm text-yellow-700 mt-1">
                  {event.warnings.map((warning, index) => (
                    <li key={index}>• {warning}</li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

function getEventDescription(eventName: string): string {
  const descriptions: Record<string, string> = {
    'Community Wellness Day': 'A comprehensive health and wellness event focusing on physical and mental health awareness',
    'Skills for Schools Mentoring': 'Educational mentoring program connecting professionals with students',
    'Beach Cleanup Initiative': 'Environmental conservation event focusing on marine ecosystem protection',
    'Policy & Ethics Training': 'Corporate governance and ethical decision-making workshop',
    'Digital Literacy Workshop': 'Technology skills training for underserved communities',
    'Sustainable Agriculture Workshop': 'Training on sustainable farming practices and food security',
    'Mental Health Awareness Campaign': 'Community mental health support and awareness program',
    'Renewable Energy Education': 'Workshop on clean energy solutions and climate action',
  };
  
  return descriptions[eventName] || 'A community event focused on positive impact';
}
