// All enums used throughout the application
export enum UserType {
  INDIVIDUAL = 'INDIVIDUAL',
  NGO = 'NGO',
  CORPORATE = 'CORPORATE',
  SCHOOL = 'SCHOOL',
  HEALTHCARE = 'HEALTHCARE',
}

export enum ParticipationStatus {
  REGISTERED = 'REGISTERED',
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  ATTENDED = 'ATTENDED',
  CANCELLED = 'CANCELLED',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum EventStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  UPCOMING = 'UPCOMING',
  ONGOING = 'ONGOING',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum EventCategory {
  VOLUNTEERING = 'VOLUNTEERING',
  WORKSHOP = 'WORKSHOP',
  FUNDRAISER = 'FUNDRAISER',
  CLEANUP = 'CLEANUP',
  AWARENESS = 'AWARENESS',
  OTHER = 'OTHER',
}

export enum VerificationType {
  ACTIVITY = 'ACTIVITY',
  EVENT = 'EVENT',
  ACHIEVEMENT = 'ACHIEVEMENT',
  CERTIFICATE = 'CERTIFICATE',
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum CertificateType {
  PARTICIPATION = 'PARTICIPATION',
  ACHIEVEMENT = 'ACHIEVEMENT',
  COMPLETION = 'COMPLETION',
  LEADERSHIP = 'LEADERSHIP',
}

export enum AchievementType {
  MILESTONE = 'MILESTONE',
  CONTRIBUTION = 'CONTRIBUTION',
  LEADERSHIP = 'LEADERSHIP',
  SPECIAL = 'SPECIAL',
}

export enum NotificationType {
  ACHIEVEMENT = 'ACHIEVEMENT',
  EVENT = 'EVENT',
  BADGE = 'BADGE',
  INVITATION = 'INVITATION',
  SYSTEM = 'SYSTEM',
  EVENT_REMINDER = 'EVENT_REMINDER',
  BADGE_EARNED = 'BADGE_EARNED',
  VERIFICATION_REQUEST = 'VERIFICATION_REQUEST',
  SUPPORT_RESPONSE = 'SUPPORT_RESPONSE',
  REFERRAL_REWARD = 'REFERRAL_REWARD',
  CUSTOM = 'CUSTOM',
  FOLLOW = 'FOLLOW',
  DONATION = 'DONATION',
  VETTING_REQUEST = 'VETTING_REQUEST',
  VETTING_RESPONSE = 'VETTING_RESPONSE',
  APPLICATION_UPDATE = 'APPLICATION_UPDATE',
  SUPPORT_TICKET = 'SUPPORT_TICKET',
  MESSAGE = 'MESSAGE',
  CERTIFICATE_ISSUED = 'CERTIFICATE_ISSUED',
  RANK_UP = 'RANK_UP',
  EVENT_JOINED = 'EVENT_JOINED',
  MONTHLY_REPORT = 'MONTHLY_REPORT',
}

export enum SubscriptionTier {
  IMPACT_STARTER = 'IMPACT_STARTER',
  COMMUNITY_BUILDER = 'COMMUNITY_BUILDER',
  COMMUNITY_ALLY = 'COMMUNITY_ALLY',
  IMPACT_DRIVER = 'IMPACT_DRIVER',
  CSR_PRACTITIONER = 'CSR_PRACTITIONER',
  CSR_LEADER = 'CSR_LEADER',
  ESG_CHAMPION = 'ESG_CHAMPION',
  TRUSTED_PARTNER = 'TRUSTED_PARTNER',
  INDUSTRY_BENCHMARK = 'INDUSTRY_BENCHMARK',
  GLOBAL_IMPACT_LEADER = 'GLOBAL_IMPACT_LEADER',
}
