// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/analytics" | "/community" | "/dashboard" | "/demo/community" | "/demo/dashboard" | "/demo/leaderboards" | "/demo/opportunities" | "/events" | "/events/[id]" | "/events/[id]/edit" | "/events/[id]/gallery" | "/events/create" | "/journey" | "/leaderboards" | "/onboarding" | "/opportunities" | "/organization" | "/organization/accept-invite" | "/organization/certificates" | "/organization/certificates/create" | "/organization/events" | "/organization/members" | "/organizations/[id]/certificates" | "/pricing" | "/profile" | "/profile-setup" | "/profile/edit" | "/settings" | "/signup"
type AppRouteHandlerRoutes = "/api/admin/stats" | "/api/auth/[...nextauth]" | "/api/auth/register" | "/api/certificates/generate" | "/api/community/stats" | "/api/events" | "/api/events/[id]" | "/api/events/[id]/participate" | "/api/leaderboards" | "/api/notifications" | "/api/organization/accept-invite" | "/api/organization/certificates/stats" | "/api/organization/certificates/templates" | "/api/organization/events" | "/api/organization/events/[id]/certificates" | "/api/organization/events/[id]/certificates/bulk-issue" | "/api/organization/events/[id]/duplicate" | "/api/organization/events/[id]/status" | "/api/organization/events/stats" | "/api/organization/members" | "/api/organization/members/[id]" | "/api/organization/members/[id]/role" | "/api/organization/members/invite" | "/api/organization/stats" | "/api/organizations/certificates" | "/api/organizations/certificates/[id]/revoke" | "/api/organizations/certificates/bulk-issue" | "/api/organizations/certificates/templates/[id]/toggle" | "/api/organizations/register" | "/api/payments/create-checkout.ts" | "/api/payments/webhook" | "/api/social/[id]/comments" | "/api/social/[id]/like" | "/api/social/posts" | "/api/socket" | "/api/users/gamification" | "/api/users/onboarding" | "/api/users/profile" | "/api/users/register" | "/api/users/score" | "/api/users/sync" | "/api/verifications" | "/api/verifications/[id]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/analytics": {}
  "/api/admin/stats": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/register": {}
  "/api/certificates/generate": {}
  "/api/community/stats": {}
  "/api/events": {}
  "/api/events/[id]": { "id": string; }
  "/api/events/[id]/participate": { "id": string; }
  "/api/leaderboards": {}
  "/api/notifications": {}
  "/api/organization/accept-invite": {}
  "/api/organization/certificates/stats": {}
  "/api/organization/certificates/templates": {}
  "/api/organization/events": {}
  "/api/organization/events/[id]/certificates": { "id": string; }
  "/api/organization/events/[id]/certificates/bulk-issue": { "id": string; }
  "/api/organization/events/[id]/duplicate": { "id": string; }
  "/api/organization/events/[id]/status": { "id": string; }
  "/api/organization/events/stats": {}
  "/api/organization/members": {}
  "/api/organization/members/[id]": { "id": string; }
  "/api/organization/members/[id]/role": { "id": string; }
  "/api/organization/members/invite": {}
  "/api/organization/stats": {}
  "/api/organizations/certificates": {}
  "/api/organizations/certificates/[id]/revoke": { "id": string; }
  "/api/organizations/certificates/bulk-issue": {}
  "/api/organizations/certificates/templates/[id]/toggle": { "id": string; }
  "/api/organizations/register": {}
  "/api/payments/create-checkout.ts": {}
  "/api/payments/webhook": {}
  "/api/social/[id]/comments": { "id": string; }
  "/api/social/[id]/like": { "id": string; }
  "/api/social/posts": {}
  "/api/socket": {}
  "/api/users/gamification": {}
  "/api/users/onboarding": {}
  "/api/users/profile": {}
  "/api/users/register": {}
  "/api/users/score": {}
  "/api/users/sync": {}
  "/api/verifications": {}
  "/api/verifications/[id]": { "id": string; }
  "/community": {}
  "/dashboard": {}
  "/demo/community": {}
  "/demo/dashboard": {}
  "/demo/leaderboards": {}
  "/demo/opportunities": {}
  "/events": {}
  "/events/[id]": { "id": string; }
  "/events/[id]/edit": { "id": string; }
  "/events/[id]/gallery": { "id": string; }
  "/events/create": {}
  "/journey": {}
  "/leaderboards": {}
  "/onboarding": {}
  "/opportunities": {}
  "/organization": {}
  "/organization/accept-invite": {}
  "/organization/certificates": {}
  "/organization/certificates/create": {}
  "/organization/events": {}
  "/organization/members": {}
  "/organizations/[id]/certificates": { "id": string; }
  "/pricing": {}
  "/profile": {}
  "/profile-setup": {}
  "/profile/edit": {}
  "/settings": {}
  "/signup": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
