// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/dist/lib/metadata/types/metadata-interface.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/page.tsx
{
  const handler = {} as typeof import("../../src/app/admin/page.js")
  handler satisfies AppPageConfig<"/admin">
}

// Validate ../../src/app/analytics/page.tsx
{
  const handler = {} as typeof import("../../src/app/analytics/page.js")
  handler satisfies AppPageConfig<"/analytics">
}

// Validate ../../src/app/community/page.tsx
{
  const handler = {} as typeof import("../../src/app/community/page.js")
  handler satisfies AppPageConfig<"/community">
}

// Validate ../../src/app/dashboard/page.tsx
{
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  handler satisfies AppPageConfig<"/dashboard">
}

// Validate ../../src/app/demo/community/page.tsx
{
  const handler = {} as typeof import("../../src/app/demo/community/page.js")
  handler satisfies AppPageConfig<"/demo/community">
}

// Validate ../../src/app/demo/dashboard/page.tsx
{
  const handler = {} as typeof import("../../src/app/demo/dashboard/page.js")
  handler satisfies AppPageConfig<"/demo/dashboard">
}

// Validate ../../src/app/demo/leaderboards/page.tsx
{
  const handler = {} as typeof import("../../src/app/demo/leaderboards/page.js")
  handler satisfies AppPageConfig<"/demo/leaderboards">
}

// Validate ../../src/app/demo/opportunities/page.tsx
{
  const handler = {} as typeof import("../../src/app/demo/opportunities/page.js")
  handler satisfies AppPageConfig<"/demo/opportunities">
}

// Validate ../../src/app/events/[id]/edit/page.tsx
{
  const handler = {} as typeof import("../../src/app/events/[id]/edit/page.js")
  handler satisfies AppPageConfig<"/events/[id]/edit">
}

// Validate ../../src/app/events/[id]/gallery/page.tsx
{
  const handler = {} as typeof import("../../src/app/events/[id]/gallery/page.js")
  handler satisfies AppPageConfig<"/events/[id]/gallery">
}

// Validate ../../src/app/events/[id]/page.tsx
{
  const handler = {} as typeof import("../../src/app/events/[id]/page.js")
  handler satisfies AppPageConfig<"/events/[id]">
}

// Validate ../../src/app/events/create/page.tsx
{
  const handler = {} as typeof import("../../src/app/events/create/page.js")
  handler satisfies AppPageConfig<"/events/create">
}

// Validate ../../src/app/events/page.tsx
{
  const handler = {} as typeof import("../../src/app/events/page.js")
  handler satisfies AppPageConfig<"/events">
}

// Validate ../../src/app/journey/page.tsx
{
  const handler = {} as typeof import("../../src/app/journey/page.js")
  handler satisfies AppPageConfig<"/journey">
}

// Validate ../../src/app/leaderboards/page.tsx
{
  const handler = {} as typeof import("../../src/app/leaderboards/page.js")
  handler satisfies AppPageConfig<"/leaderboards">
}

// Validate ../../src/app/onboarding/page.tsx
{
  const handler = {} as typeof import("../../src/app/onboarding/page.js")
  handler satisfies AppPageConfig<"/onboarding">
}

// Validate ../../src/app/opportunities/page.tsx
{
  const handler = {} as typeof import("../../src/app/opportunities/page.js")
  handler satisfies AppPageConfig<"/opportunities">
}

// Validate ../../src/app/organization/accept-invite/page.tsx
{
  const handler = {} as typeof import("../../src/app/organization/accept-invite/page.js")
  handler satisfies AppPageConfig<"/organization/accept-invite">
}

// Validate ../../src/app/organization/certificates/create/page.tsx
{
  const handler = {} as typeof import("../../src/app/organization/certificates/create/page.js")
  handler satisfies AppPageConfig<"/organization/certificates/create">
}

// Validate ../../src/app/organization/certificates/page.tsx
{
  const handler = {} as typeof import("../../src/app/organization/certificates/page.js")
  handler satisfies AppPageConfig<"/organization/certificates">
}

// Validate ../../src/app/organization/events/page.tsx
{
  const handler = {} as typeof import("../../src/app/organization/events/page.js")
  handler satisfies AppPageConfig<"/organization/events">
}

// Validate ../../src/app/organization/members/page.tsx
{
  const handler = {} as typeof import("../../src/app/organization/members/page.js")
  handler satisfies AppPageConfig<"/organization/members">
}

// Validate ../../src/app/organization/page.tsx
{
  const handler = {} as typeof import("../../src/app/organization/page.js")
  handler satisfies AppPageConfig<"/organization">
}

// Validate ../../src/app/organizations/[id]/certificates/page.tsx
{
  const handler = {} as typeof import("../../src/app/organizations/[id]/certificates/page.js")
  handler satisfies AppPageConfig<"/organizations/[id]/certificates">
}

// Validate ../../src/app/page.tsx
{
  const handler = {} as typeof import("../../src/app/page.js")
  handler satisfies AppPageConfig<"/">
}

// Validate ../../src/app/pricing/page.tsx
{
  const handler = {} as typeof import("../../src/app/pricing/page.js")
  handler satisfies AppPageConfig<"/pricing">
}

// Validate ../../src/app/profile-setup/page.tsx
{
  const handler = {} as typeof import("../../src/app/profile-setup/page.js")
  handler satisfies AppPageConfig<"/profile-setup">
}

// Validate ../../src/app/profile/edit/page.tsx
{
  const handler = {} as typeof import("../../src/app/profile/edit/page.js")
  handler satisfies AppPageConfig<"/profile/edit">
}

// Validate ../../src/app/profile/page.tsx
{
  const handler = {} as typeof import("../../src/app/profile/page.js")
  handler satisfies AppPageConfig<"/profile">
}

// Validate ../../src/app/settings/page.tsx
{
  const handler = {} as typeof import("../../src/app/settings/page.js")
  handler satisfies AppPageConfig<"/settings">
}

// Validate ../../src/app/signup/page.tsx
{
  const handler = {} as typeof import("../../src/app/signup/page.js")
  handler satisfies AppPageConfig<"/signup">
}

// Validate ../../src/app/api/admin/stats/route.ts
{
  const handler = {} as typeof import("../../src/app/api/admin/stats/route.js")
  handler satisfies RouteHandlerConfig<"/api/admin/stats">
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  handler satisfies RouteHandlerConfig<"/api/auth/[...nextauth]">
}

// Validate ../../src/app/api/auth/register/route.ts
{
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  handler satisfies RouteHandlerConfig<"/api/auth/register">
}

// Validate ../../src/app/api/certificates/generate/route.ts
{
  const handler = {} as typeof import("../../src/app/api/certificates/generate/route.js")
  handler satisfies RouteHandlerConfig<"/api/certificates/generate">
}

// Validate ../../src/app/api/community/stats/route.ts
{
  const handler = {} as typeof import("../../src/app/api/community/stats/route.js")
  handler satisfies RouteHandlerConfig<"/api/community/stats">
}

// Validate ../../src/app/api/events/[id]/participate/route.ts
{
  const handler = {} as typeof import("../../src/app/api/events/[id]/participate/route.js")
  handler satisfies RouteHandlerConfig<"/api/events/[id]/participate">
}

// Validate ../../src/app/api/events/[id]/route.ts
{
  const handler = {} as typeof import("../../src/app/api/events/[id]/route.js")
  handler satisfies RouteHandlerConfig<"/api/events/[id]">
}

// Validate ../../src/app/api/events/route.ts
{
  const handler = {} as typeof import("../../src/app/api/events/route.js")
  handler satisfies RouteHandlerConfig<"/api/events">
}

// Validate ../../src/app/api/leaderboards/route.ts
{
  const handler = {} as typeof import("../../src/app/api/leaderboards/route.js")
  handler satisfies RouteHandlerConfig<"/api/leaderboards">
}

// Validate ../../src/app/api/notifications/route.ts
{
  const handler = {} as typeof import("../../src/app/api/notifications/route.js")
  handler satisfies RouteHandlerConfig<"/api/notifications">
}

// Validate ../../src/app/api/organization/accept-invite/route.ts
{
  const handler = {} as typeof import("../../src/app/api/organization/accept-invite/route.js")
  handler satisfies RouteHandlerConfig<"/api/organization/accept-invite">
}

// Validate ../../src/app/api/organization/certificates/stats/route.ts
{
  const handler = {} as typeof import("../../src/app/api/organization/certificates/stats/route.js")
  handler satisfies RouteHandlerConfig<"/api/organization/certificates/stats">
}

// Validate ../../src/app/api/organization/certificates/templates/route.ts
{
  const handler = {} as typeof import("../../src/app/api/organization/certificates/templates/route.js")
  handler satisfies RouteHandlerConfig<"/api/organization/certificates/templates">
}

// Validate ../../src/app/api/organization/events/[id]/certificates/bulk-issue/route.ts
{
  const handler = {} as typeof import("../../src/app/api/organization/events/[id]/certificates/bulk-issue/route.js")
  handler satisfies RouteHandlerConfig<"/api/organization/events/[id]/certificates/bulk-issue">
}

// Validate ../../src/app/api/organization/events/[id]/certificates/route.ts
{
  const handler = {} as typeof import("../../src/app/api/organization/events/[id]/certificates/route.js")
  handler satisfies RouteHandlerConfig<"/api/organization/events/[id]/certificates">
}

// Validate ../../src/app/api/organization/events/[id]/duplicate/route.ts
{
  const handler = {} as typeof import("../../src/app/api/organization/events/[id]/duplicate/route.js")
  handler satisfies RouteHandlerConfig<"/api/organization/events/[id]/duplicate">
}

// Validate ../../src/app/api/organization/events/[id]/status/route.ts
{
  const handler = {} as typeof import("../../src/app/api/organization/events/[id]/status/route.js")
  handler satisfies RouteHandlerConfig<"/api/organization/events/[id]/status">
}

// Validate ../../src/app/api/organization/events/route.ts
{
  const handler = {} as typeof import("../../src/app/api/organization/events/route.js")
  handler satisfies RouteHandlerConfig<"/api/organization/events">
}

// Validate ../../src/app/api/organization/events/stats/route.ts
{
  const handler = {} as typeof import("../../src/app/api/organization/events/stats/route.js")
  handler satisfies RouteHandlerConfig<"/api/organization/events/stats">
}

// Validate ../../src/app/api/organization/members/[id]/role/route.ts
{
  const handler = {} as typeof import("../../src/app/api/organization/members/[id]/role/route.js")
  handler satisfies RouteHandlerConfig<"/api/organization/members/[id]/role">
}

// Validate ../../src/app/api/organization/members/[id]/route.ts
{
  const handler = {} as typeof import("../../src/app/api/organization/members/[id]/route.js")
  handler satisfies RouteHandlerConfig<"/api/organization/members/[id]">
}

// Validate ../../src/app/api/organization/members/invite/route.ts
{
  const handler = {} as typeof import("../../src/app/api/organization/members/invite/route.js")
  handler satisfies RouteHandlerConfig<"/api/organization/members/invite">
}

// Validate ../../src/app/api/organization/members/route.ts
{
  const handler = {} as typeof import("../../src/app/api/organization/members/route.js")
  handler satisfies RouteHandlerConfig<"/api/organization/members">
}

// Validate ../../src/app/api/organization/stats/route.ts
{
  const handler = {} as typeof import("../../src/app/api/organization/stats/route.js")
  handler satisfies RouteHandlerConfig<"/api/organization/stats">
}

// Validate ../../src/app/api/organizations/certificates/[id]/revoke/route.ts
{
  const handler = {} as typeof import("../../src/app/api/organizations/certificates/[id]/revoke/route.js")
  handler satisfies RouteHandlerConfig<"/api/organizations/certificates/[id]/revoke">
}

// Validate ../../src/app/api/organizations/certificates/bulk-issue/route.ts
{
  const handler = {} as typeof import("../../src/app/api/organizations/certificates/bulk-issue/route.js")
  handler satisfies RouteHandlerConfig<"/api/organizations/certificates/bulk-issue">
}

// Validate ../../src/app/api/organizations/certificates/route.ts
{
  const handler = {} as typeof import("../../src/app/api/organizations/certificates/route.js")
  handler satisfies RouteHandlerConfig<"/api/organizations/certificates">
}

// Validate ../../src/app/api/organizations/certificates/templates/[id]/toggle/route.ts
{
  const handler = {} as typeof import("../../src/app/api/organizations/certificates/templates/[id]/toggle/route.js")
  handler satisfies RouteHandlerConfig<"/api/organizations/certificates/templates/[id]/toggle">
}

// Validate ../../src/app/api/organizations/register/route.ts
{
  const handler = {} as typeof import("../../src/app/api/organizations/register/route.js")
  handler satisfies RouteHandlerConfig<"/api/organizations/register">
}

// Validate ../../src/app/api/payments/create-checkout.ts/route.ts
{
  const handler = {} as typeof import("../../src/app/api/payments/create-checkout.ts/route.js")
  handler satisfies RouteHandlerConfig<"/api/payments/create-checkout.ts">
}

// Validate ../../src/app/api/payments/webhook/route.ts
{
  const handler = {} as typeof import("../../src/app/api/payments/webhook/route.js")
  handler satisfies RouteHandlerConfig<"/api/payments/webhook">
}

// Validate ../../src/app/api/social/[id]/comments/route.ts
{
  const handler = {} as typeof import("../../src/app/api/social/[id]/comments/route.js")
  handler satisfies RouteHandlerConfig<"/api/social/[id]/comments">
}

// Validate ../../src/app/api/social/[id]/like/route.ts
{
  const handler = {} as typeof import("../../src/app/api/social/[id]/like/route.js")
  handler satisfies RouteHandlerConfig<"/api/social/[id]/like">
}

// Validate ../../src/app/api/social/posts/route.ts
{
  const handler = {} as typeof import("../../src/app/api/social/posts/route.js")
  handler satisfies RouteHandlerConfig<"/api/social/posts">
}

// Validate ../../src/app/api/socket/route.ts
{
  const handler = {} as typeof import("../../src/app/api/socket/route.js")
  handler satisfies RouteHandlerConfig<"/api/socket">
}

// Validate ../../src/app/api/users/gamification/route.ts
{
  const handler = {} as typeof import("../../src/app/api/users/gamification/route.js")
  handler satisfies RouteHandlerConfig<"/api/users/gamification">
}

// Validate ../../src/app/api/users/onboarding/route.ts
{
  const handler = {} as typeof import("../../src/app/api/users/onboarding/route.js")
  handler satisfies RouteHandlerConfig<"/api/users/onboarding">
}

// Validate ../../src/app/api/users/profile/route.ts
{
  const handler = {} as typeof import("../../src/app/api/users/profile/route.js")
  handler satisfies RouteHandlerConfig<"/api/users/profile">
}

// Validate ../../src/app/api/users/register/route.ts
{
  const handler = {} as typeof import("../../src/app/api/users/register/route.js")
  handler satisfies RouteHandlerConfig<"/api/users/register">
}

// Validate ../../src/app/api/users/score/route.ts
{
  const handler = {} as typeof import("../../src/app/api/users/score/route.js")
  handler satisfies RouteHandlerConfig<"/api/users/score">
}

// Validate ../../src/app/api/users/sync/route.ts
{
  const handler = {} as typeof import("../../src/app/api/users/sync/route.js")
  handler satisfies RouteHandlerConfig<"/api/users/sync">
}

// Validate ../../src/app/api/verifications/[id]/route.ts
{
  const handler = {} as typeof import("../../src/app/api/verifications/[id]/route.js")
  handler satisfies RouteHandlerConfig<"/api/verifications/[id]">
}

// Validate ../../src/app/api/verifications/route.ts
{
  const handler = {} as typeof import("../../src/app/api/verifications/route.js")
  handler satisfies RouteHandlerConfig<"/api/verifications">
}





// Validate ../../src/app/layout.tsx
{
  const handler = {} as typeof import("../../src/app/layout.js")
  handler satisfies LayoutConfig<"/">
}
